#!/bin/sh

if [ ! -e "/etc/bloonix/agent/sudoers.d" ] ; then
    mkdir -p /etc/bloonix/agent/sudoers.d
    chown root:root /etc/bloonix/agent/sudoers.d
    chmod 755 /etc/bloonix/agent/sudoers.d
fi

if [ ! -e "/etc/bloonix/agent/sudoers.d/check-postfix" ] ; then
    cp -a /usr/lib/bloonix/etc/sudoers.d/check-postfix /etc/bloonix/agent/sudoers.d/
    chmod 440 /etc/bloonix/agent/sudoers.d/check-postfix
fi

